# EDA INICIAL

### Carga de Datos

In [2]:
import pandas as pd 

#Paths

path_roque = "/Users/roquemorales/Desktop/DATA_CRIPTO/Dataset Académico de Cifrado en PCs.xlsx" 
path_mena = "/Users/danimena/Desktop/OneDrive_1_10-6-2026/Dataset Académico de Cifrado en PCs.xlsx"

In [7]:
#Carga 

data = pd.read_excel(path_roque, header = 2)

data.head()

,EquipoID,UsuarioID,País,Región,Sistema Operativo,Versión SO,Estado TPM,Encryption Readiness,Estado de Cifrado,Tecnología de cifrado State,...,Banda Antigüedad,Estado de Cuenta,Mes Último Logon,Banda Recencia,Estado Hardware,Tipo de Red,Fuente de Datos,En MDM,En AD,En MacOS
0,PC-0001,U-0001,Argentina,Sudamérica,Windows,10.0.26100.x,TPM 2,Ready,Encrypted,Success,...,No disponible,Habilitada,2025-11,0-30 días,No disponible,No disponible,MDM + AD,Sí,Sí,No
1,PC-0002,No asignado,Argentina,Sudamérica,Windows,Windows 10,No disponible,No disponible,No disponible,No disponible,...,No disponible,Habilitada,2025-06,91-180 días,No disponible,No disponible,AD,No,Sí,No
2,PC-0003,U-0002,Argentina,Sudamérica,Windows,10.0.19045.x,TPM 2,Ready,Encrypted,Success,...,No disponible,Habilitada,2025-11,0-30 días,No disponible,No disponible,MDM + AD,Sí,Sí,No
3,PC-0004,U-0003,Argentina,Sudamérica,Windows,10.0.26100.x,TPM 2,Ready,Encrypted,Success,...,No disponible,Habilitada,2025-11,0-30 días,No disponible,No disponible,MDM + AD,Sí,Sí,No
4,PC-0005,No asignado,Argentina,Sudamérica,Windows,Windows 11,No disponible,No disponible,No disponible,No disponible,...,No disponible,Habilitada,2025-11,0-30 días,No disponible,No disponible,AD,No,Sí,No

In [9]:
#Columnas 

print (data.columns)

Index(['EquipoID', 'UsuarioID', 'País', 'Región', 'Sistema Operativo',
       'Versión SO', 'Estado TPM', 'Encryption Readiness', 'Estado de Cifrado',
       'Tecnología de cifrado State', 'Estado de Cumplimiento',
       'Categoría de Equipo', 'Clase de Equipo', 'Perfil de Privilegio',
       'Antigüedad Meses', 'Banda Antigüedad', 'Estado de Cuenta',
       'Mes Último Logon', 'Banda Recencia', 'Estado Hardware', 'Tipo de Red',
       'Fuente de Datos', 'En MDM', 'En AD', 'En MacOS'],
      dtype='str')

In [8]:
#Carga

data = pd.read_excel(path_mena, header = 2)

data.head()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/danimena/Desktop/OneDrive_1_10-6-2026/Dataset Académico de Cifrado en PCs.xlsx'

In [12]:
data_raw = data.copy()

data_raw.head()

,EquipoID,UsuarioID,País,Región,Sistema Operativo,Versión SO,Estado TPM,Encryption Readiness,Estado de Cifrado,Tecnología de cifrado State,...,Banda Antigüedad,Estado de Cuenta,Mes Último Logon,Banda Recencia,Estado Hardware,Tipo de Red,Fuente de Datos,En MDM,En AD,En MacOS
0,PC-0001,U-0001,Argentina,Sudamérica,Windows,10.0.26100.x,TPM 2,Ready,Encrypted,Success,...,No disponible,Habilitada,2025-11,0-30 días,No disponible,No disponible,MDM + AD,Sí,Sí,No
1,PC-0002,No asignado,Argentina,Sudamérica,Windows,Windows 10,No disponible,No disponible,No disponible,No disponible,...,No disponible,Habilitada,2025-06,91-180 días,No disponible,No disponible,AD,No,Sí,No
2,PC-0003,U-0002,Argentina,Sudamérica,Windows,10.0.19045.x,TPM 2,Ready,Encrypted,Success,...,No disponible,Habilitada,2025-11,0-30 días,No disponible,No disponible,MDM + AD,Sí,Sí,No
3,PC-0004,U-0003,Argentina,Sudamérica,Windows,10.0.26100.x,TPM 2,Ready,Encrypted,Success,...,No disponible,Habilitada,2025-11,0-30 días,No disponible,No disponible,MDM + AD,Sí,Sí,No
4,PC-0005,No asignado,Argentina,Sudamérica,Windows,Windows 11,No disponible,No disponible,No disponible,No disponible,...,No disponible,Habilitada,2025-11,0-30 días,No disponible,No disponible,AD,No,Sí,No

In [11]:

#Perfil del DF 
def perfil(df, cols):
    return pd.DataFrame({
        "tipo": df[cols].dtypes.astype(str),
        "nulos_%": (df[cols].isna().mean() * 100).round(1),
        "unicos": df[cols].nunique(),
        "top_5": [df[c].value_counts(dropna=False).head(5).to_dict() for c in cols],
    })

#Normalizar textos 
def norm_txt(s):
    """quita espacios, pasa a minúsculas y convierte los falsos nulos en NA"""
    s = s.astype("string").str.strip().str.lower()
    return s.replace({"": pd.NA, "n/a": pd.NA, "na": pd.NA, "null": pd.NA, "-": pd.NA, "none": pd.NA})

#Mapeo
def mapear(s, mapa, nombre):
    """aplica el mapeo y falla si aparece un valor no contemplado"""
    s = norm_txt(s)
    sin_mapear = set(s.dropna().unique()) - set(mapa)
    assert not sin_mapear, f"{nombre}: valores sin mapear {sin_mapear}"
    return s.map(mapa)